#!/usr/bin/env node
/**
 * Render an OpenAPI 3.1 document into a single, GitHub-readable reference.md.
 *
 * Dependency-free (Node stdlib only). Reads an openapi.json and writes curated
 * markdown: an endpoint section grouped by tag, then a Schemas section with one
 * field table per component. `$ref`s become in-page anchor links.
 *
 * Usage:  node scripts/render-openapi.mjs <openapi.json> <out.md>
 */
import { readFileSync, writeFileSync } from 'node:fs'

const [, , specPath, outPath] = process.argv
if (!specPath || !outPath) {
  console.error('usage: node scripts/render-openapi.mjs <openapi.json> <out.md>')
  process.exit(1)
}

const spec = JSON.parse(readFileSync(specPath, 'utf8'))
const schemas = spec.components?.schemas ?? {}
const securitySchemes = spec.components?.securitySchemes ?? {}

const anchor = (name) => `schema-${name.toLowerCase()}`
const refName = (ref) => ref.split('/').pop()
const esc = (s) => String(s).replace(/\|/g, '\\|').replace(/\n+/g, ' ').trim()

/** Human-readable type label for a schema node; `$ref` → anchor link. */
function typeLabel(s) {
  if (!s) return 'any'
  if (typeof s === 'boolean') return s ? 'unknown' : 'never'
  if (Object.keys(s).length === 0) return 'unknown' // empty schema = any JSON value
  if (s.$ref) {
    const n = refName(s.$ref)
    return `[\`${n}\`](#${anchor(n)})`
  }
  if (s.enum) return s.enum.map((v) => `\`${JSON.stringify(v)}\``).join(' \\| ')
  if (s.anyOf || s.oneOf) return (s.anyOf || s.oneOf).map(typeLabel).join(' \\| ')
  if (s.const !== undefined) return `\`${JSON.stringify(s.const)}\``
  if (s.type === 'array') return `array&lt;${typeLabel(s.items)}&gt;`
  if (s.type === 'object' && s.additionalProperties) {
    return `object&lt;string, ${typeLabel(s.additionalProperties)}&gt;`
  }
  if (Array.isArray(s.type)) return s.type.join(' \\| ')
  if (s.format) return `${s.type} (${s.format})`
  return s.type ?? 'object'
}

/** Field table rows for an object schema. */
function objectRows(s) {
  const props = s.properties ?? {}
  const required = new Set(s.required ?? [])
  return Object.entries(props).map(([name, p]) => ({
    name,
    type: typeLabel(p),
    required: required.has(name) ? 'yes' : 'no',
    desc: esc(p.description ?? ''),
  }))
}

function fieldTable(s) {
  const rows = objectRows(s)
  if (!rows.length) return '_No fields._\n'
  const head = '| Field | Type | Required | Description |\n|---|---|---|---|\n'
  return (
    head +
    rows.map((r) => `| \`${r.name}\` | ${r.type} | ${r.required} | ${r.desc} |`).join('\n') +
    '\n'
  )
}

/** Compact label for a request/response body — recognises the BaseResponse envelope. */
function bodyLabel(s) {
  if (!s) return '_empty_'
  if (s.$ref) return typeLabel(s)
  if (s.type === 'array') return `array of ${typeLabel(s.items)}`
  const keys = Object.keys(s.properties ?? {})
  const isEnvelope =
    keys.length === 4 && ['code', 'msg', 'data', 'timestamp'].every((k) => keys.includes(k))
  if (isEnvelope) {
    return `envelope \`{ code, msg, data, timestamp }\` — \`data\`: ${typeLabel(s.properties.data)}`
  }
  return null // signal: render an inline field table
}

const isInlineObject = (s) => s && s.type === 'object' && s.properties

const out = []
const p = (s = '') => out.push(s)

/**
 * Emit a schema as a field table, recursing into inline nested objects (which the
 * spec leaves anonymous) as `Parent.field` sub-tables. `$ref` nodes are linked, not
 * expanded — the referenced component renders once under its own heading.
 */
function emitSchema(title, schema, level) {
  const h = '#'.repeat(level)
  let node = schema
  let suffix = ''
  while (node && node.type === 'array') {
    suffix += '[]'
    node = node.items
  }
  p(`${h} ${title}${suffix}`)
  p('')
  if (node?.description) {
    p(esc(node.description))
    p('')
  }
  if (node?.$ref) {
    p(`See ${typeLabel(node)}.`)
    p('')
    return
  }
  if (!isInlineObject(node)) {
    p(`Type: ${typeLabel(node)}`)
    p('')
    return
  }
  p(fieldTable(node))
  for (const [fname, fp] of Object.entries(node.properties)) {
    let inner = fp
    while (inner && inner.type === 'array') inner = inner.items
    if (isInlineObject(inner)) emitSchema(`${title}${suffix}.${fname}`, fp, level + 1)
  }
}

// ── Header ───────────────────────────────────────────────────────────────────
p('<!-- GENERATED by scripts/render-openapi.mjs from docs/api/openapi.json. Do not edit by hand. -->')
p('')
p(`# ${spec.info.title} — API Reference`)
p('')
if (spec.info.version) p(`**Version:** \`${spec.info.version}\``)
p('')
if (spec.info.description) {
  p(spec.info.description)
  p('')
}
if (spec.servers?.length) {
  p('**Servers**')
  p('')
  for (const sv of spec.servers) p(`- \`${sv.url}\`${sv.description ? ` — ${sv.description}` : ''}`)
  p('')
}

// ── Authentication ─────────────────────────────────────────────────────────────
if (Object.keys(securitySchemes).length) {
  p('## Authentication')
  p('')
  for (const [name, sc] of Object.entries(securitySchemes)) {
    const kind =
      sc.type === 'http' ? `HTTP ${sc.scheme}` : sc.type === 'apiKey' ? `API key (${sc.in} \`${sc.name}\`)` : sc.type
    p(`### \`${name}\``)
    p('')
    p(`**Type:** ${kind}`)
    p('')
    if (sc.description) {
      p(sc.description)
      p('')
    }
  }
}

// ── Endpoints, grouped by tag ───────────────────────────────────────────────────
const METHODS = ['get', 'post', 'put', 'patch', 'delete']
const ops = []
for (const [path, item] of Object.entries(spec.paths ?? {})) {
  for (const m of METHODS) {
    if (item[m]) ops.push({ path, method: m, op: item[m] })
  }
}
const tags = [...new Set(ops.flatMap((o) => o.op.tags ?? ['Other']))]

p('## Endpoints')
p('')
for (const tag of tags) {
  p(`### ${tag}`)
  p('')
  for (const { path, method, op } of ops.filter((o) => (o.op.tags ?? ['Other']).includes(tag))) {
    p(`#### \`${method.toUpperCase()} ${path}\``)
    p('')
    if (op.summary) {
      p(`**${op.summary}**`)
      p('')
    }
    if (op.description) {
      p(op.description)
      p('')
    }
    const sec = (op.security ?? []).flatMap((r) => Object.keys(r))
    p(`**Auth:** ${sec.length ? sec.map((s) => `\`${s}\``).join(', ') : 'none (public)'}`)
    p('')

    // Parameters
    const params = op.parameters ?? []
    if (params.length) {
      p('**Parameters**')
      p('')
      p('| Name | In | Type | Required | Description |')
      p('|---|---|---|---|---|')
      for (const pa of params) {
        p(
          `| \`${pa.name}\` | ${pa.in} | ${typeLabel(pa.schema)} | ${pa.required ? 'yes' : 'no'} | ${esc(pa.description ?? '')} |`,
        )
      }
      p('')
    }

    // Request body
    const reqSchema = op.requestBody?.content?.['application/json']?.schema
    if (reqSchema) {
      p('**Request body**')
      p('')
      const label = bodyLabel(reqSchema)
      if (label) {
        p(label)
        p('')
      } else {
        p(fieldTable(reqSchema))
      }
    }

    // Responses
    p('**Responses**')
    p('')
    for (const [code, resp] of Object.entries(op.responses ?? {})) {
      const rs = resp.content?.['application/json']?.schema
      const label = rs ? bodyLabel(rs) : null
      const tail = rs ? ` — ${label ?? typeLabel(rs)}` : ''
      p(`- **${code}** ${esc(resp.description ?? '')}${tail}`)
    }
    p('')
  }
}

// ── Schemas ──────────────────────────────────────────────────────────────────
if (Object.keys(schemas).length) {
  p('## Schemas')
  p('')
  for (const [name, s] of Object.entries(schemas)) {
    p(`<a id="${anchor(name)}"></a>`)
    p('')
    emitSchema(`\`${name}\``, s, 3)
  }
}

writeFileSync(outPath, `${out.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd()}\n`)
console.error(`wrote ${outPath} (${ops.length} operations, ${Object.keys(schemas).length} schemas)`)
